name: Organizational Github Actions Publisher
on:
 push:
   branches: [ 'develop',  'master' ]
   paths:
   - 'templates/**'
jobs:
  publish-workflow-template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_repo: [ 'microservice-A' , 'microservice-B' ]
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/${{ matrix.target_repo }}
          path: ${{ matrix.target_repo }}
          token: ${{ secrets.RW_REPO}}
          ref: master
      - name: Update Actions
        shell: bash
        run: |
          mkdir -p .github/workflows/
          cp ../main/templates/* .github/workflows/
        working-directory: ./${{ matrix.target_repo }}
      - name: Publish workflows
        shell: bash
        run: |
          git config --local user.email "cs-minion@carbynestack.io"
          git config --local user.name "cs-minion"
          git add .
          git commit -m "Updating GitHub Actions from the origanization .github repo"
          git push
        working-directory: ./${{ matrix.target_repo }}
