name: Organizational Github Actions Publisher
on:
 push:
   branches: [ 'main' ]
   paths:
   - 'templates/**'
 workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
jobs:
  publish-workflow-template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_repo: [ 'microservice-A' , 'microservice-B' ]
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          path: main
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/${{ matrix.target_repo }}
          path: ${{ matrix.target_repo }}
          ref: main
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Update Actions
        shell: bash
        run: |
          mkdir -p .github/workflows/
          cp ../main/templates/* .github/workflows/
        working-directory: ./${{ matrix.target_repo }}
      - name: Publish workflows
        shell: bash
        run: |
          git config --local user.name "jareds-minion"
          git add .
          git commit -m "Updating GitHub Actions from the origanization .github repo"
        working-directory: ./${{ matrix.target_repo }}
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: ./${{ matrix.target_repo }}
          repository: ${{ github.repository_owner }}/${{ matrix.target_repo }}
          branch: main
          github_token: ${{ JAREDS_MINION_PAT }}
